/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantillapantallasproyecto2basedatosavanzadas;

import botonesTabla.botonRenderizador;
import botonesTabla.seleccionadorBoton;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.itson.DAO.TramitesDAO;
import org.itson.dominio.Licencia;
import org.itson.dominio.Persona;
import org.itson.dominio.Placa;
import utilidades.Ventana;

/**
 *
 * @author Zaurus
 */
public class HistorialTramitesMostrar extends javax.swing.JFrame {

    
    private Persona persona;
     private List<Placa> listaPlacas;
     private List<Licencia> listaLicencias ;
    /**
     * Creates new form TramiteLicencia
     */
    public HistorialTramitesMostrar(Persona persona) {
        initComponents();
        this.setVisible(true);
        this.persona = persona;
        this.listaPlacas = new ArrayList<>();
        this.listaLicencias = new ArrayList<>();
        String informacion = persona.getRfc() + " " + persona.getNombre() + " "
                + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno();
        this.jLbPersona.setText(informacion);
    }
    public void llenarLicenciasTabla(){
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
        TramitesDAO tramitesDAO = new TramitesDAO();
        listaLicencias = tramitesDAO.buscarLicencias(persona);
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tlbHistorial.getModel();
        modeloTabla.setRowCount(0);
        for (Licencia licencia : listaLicencias) {
            Object[] fila = {
                licencia.getId(),
                licencia.getEstado(),
                formateador.format(licencia.getFechaExpedicion().getTime()),
                formateador.format(licencia.getVigencia().getTime()) 
            };
            modeloTabla.addRow(fila);
        }
        tlbHistorial.getColumnModel().getColumn(4).setCellRenderer(new botonRenderizador());
        tlbHistorial.getColumnModel().getColumn(4).setCellEditor(new seleccionadorBoton());
        tlbHistorial.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int bandera =1;
                int columna = tlbHistorial.getColumnModel().getColumnIndexAtX(e.getX());
                int fila = e.getY() / tlbHistorial.getRowHeight();
                if (columna == 4 && fila < tlbHistorial.getRowCount() && fila >= 0) {
                    botonActionPerformed(fila,1);
                }
            }
        });
    }
    public void llenarPlacasTabla(){
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
        TramitesDAO tramitesDAO = new TramitesDAO();
        listaPlacas = tramitesDAO.buscarPlacas(persona);
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tlbHistorial.getModel();
        modeloTabla.setRowCount(0);
        for (Placa placas : listaPlacas) {
            Object[] fila = {
                placas.getId(),
                placas.getEstado(),
                formateador.format(placas.getFechaExpedicion().getTime()),
                formateador.format(placas.getVigencia().getTime()) 
            };
            modeloTabla.addRow(fila);
        }
        tlbHistorial.getColumnModel().getColumn(4).setCellRenderer(new botonRenderizador());
        tlbHistorial.getColumnModel().getColumn(4).setCellEditor(new seleccionadorBoton());
        tlbHistorial.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int bandera =0;
                int columna = tlbHistorial.getColumnModel().getColumnIndexAtX(e.getX());
                int fila = e.getY() / tlbHistorial.getRowHeight();
                if (columna == 4 && fila < tlbHistorial.getRowCount() && fila >= 0) {
                    botonActionPerformed(fila,bandera);
                }
            }
        });
    }
     public void mostrarMensajeInformacionPlaca(Placa placa) {
        JOptionPane.showMessageDialog(this,  placa);
    }
      public void mostrarMensajeInformacionLicencia(Licencia licencia) {
        JOptionPane.showMessageDialog(this, licencia);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipoTramite = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLbPersona = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jrbLicencia = new javax.swing.JRadioButton();
        jrbPlacas = new javax.swing.JRadioButton();
        btnInicio = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLbHistorial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbHistorial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(564, 564));

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));

        jLbPersona.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLbPersona.setForeground(new java.awt.Color(255, 255, 255));
        jLbPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historial de Tramites");

        jrbLicencia.setBackground(new java.awt.Color(0, 51, 0));
        btgTipoTramite.add(jrbLicencia);
        jrbLicencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jrbLicencia.setForeground(new java.awt.Color(255, 255, 255));
        jrbLicencia.setText("Licencias");
        jrbLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLicenciaActionPerformed(evt);
            }
        });

        jrbPlacas.setBackground(new java.awt.Color(0, 51, 0));
        btgTipoTramite.add(jrbPlacas);
        jrbPlacas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jrbPlacas.setForeground(new java.awt.Color(255, 255, 255));
        jrbPlacas.setText("Placas");
        jrbPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPlacasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jrbLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbLicencia)
                    .addComponent(jrbPlacas))
                .addGap(25, 25, 25))
        );

        btnInicio.setBackground(new java.awt.Color(153, 0, 51));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(153, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLbHistorial.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLbHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tlbHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Estado", "Fecha Expedicion", "Vigencia", "Mas informacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tlbHistorial);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLbHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLbHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void buscarPlaca(int id){
        for (Placa placas : listaPlacas) {
            if(placas.getId() == id){
                this.mostrarMensajeInformacionPlaca(placas);
            }
        }
    }
    public void buscarLicencia(int id){
        for (Licencia licencias : listaLicencias) {
            if(licencias.getId() == id){
                this.mostrarMensajeInformacionLicencia(licencias);
            }
        }
    }
    
    private void botonActionPerformed(int fila,int bandera) {
        int filaSeleccionada = tlbHistorial.getSelectedRow();
        List<Object> valoresFila = new ArrayList<>();
        for (int i = 0; i < tlbHistorial.getColumnCount(); i++) {
            Object valor = tlbHistorial.getValueAt(filaSeleccionada, i);
            valoresFila.add(valor);
        }
        int id = Integer.parseInt(valoresFila.get(0).toString());
        if (bandera == 0){
            this.buscarPlaca(id);
        }else{
            this.buscarLicencia(id);
        }
    }
    
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.dispose();
        new MenuInicio();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        BusquedaPersona busquedaPersona = new BusquedaPersona(Ventana.HISTORIALTRAMITES);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jrbLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLicenciaActionPerformed
        this.jLbHistorial.setText("Historial Licencias");
        this.llenarLicenciasTabla();
    }//GEN-LAST:event_jrbLicenciaActionPerformed

    private void jrbPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPlacasActionPerformed
         this.jLbHistorial.setText("Historial Placas");
         this.llenarPlacasTabla();
    }//GEN-LAST:event_jrbPlacasActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipoTramite;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbHistorial;
    private javax.swing.JLabel jLbPersona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbLicencia;
    private javax.swing.JRadioButton jrbPlacas;
    private javax.swing.JTable tlbHistorial;
    // End of variables declaration//GEN-END:variables
}
