/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantillapantallasproyecto2basedatosavanzadas;

import excepciones.PersistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.itson.DAO.PersonasDAO;
import utilidades.Ventana;

/**
 *
 * @author Julio Chon, Luis Ayon
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Metodo que inicializa los objetos del formulario.
     */
    public MenuInicio() {
        initComponents();
        this.setVisible(true);
    }
    /**
     * Metodo que muestra un jOptionPane avisando que las personas fueron agregadas correctamente.
     */
    public void mostrarMensajePersonasGuardadas() {
        JOptionPane.showMessageDialog(this, "Personas agregadas correctamente",
                "Completado", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * Metodo que muestra un jOptionPane avisando que las personas fueron agregadas anteriormente.
     */
     public void mostrarMensajePersonasError() {
        JOptionPane.showMessageDialog(this, "Las personas ya fueron agregadas",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTramiteLicencia = new javax.swing.JButton();
        btnRegistrarPersonas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnTramitePlacas = new javax.swing.JButton();
        btnHistorialTramites = new javax.swing.JButton();
        btnRegistrarVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel1.setPreferredSize(new java.awt.Dimension(564, 564));

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de tramites del estado de Sonora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        btnTramiteLicencia.setBackground(new java.awt.Color(153, 0, 51));
        btnTramiteLicencia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTramiteLicencia.setForeground(new java.awt.Color(255, 255, 255));
        btnTramiteLicencia.setText("Tramite Licencia");
        btnTramiteLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramiteLicenciaActionPerformed(evt);
            }
        });

        btnRegistrarPersonas.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrarPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPersonas.setText("Registrar(Personas)");
        btnRegistrarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonasActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(153, 0, 51));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes de tramites");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnTramitePlacas.setBackground(new java.awt.Color(153, 0, 51));
        btnTramitePlacas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTramitePlacas.setForeground(new java.awt.Color(255, 255, 255));
        btnTramitePlacas.setText("Tramite Placas");
        btnTramitePlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitePlacasActionPerformed(evt);
            }
        });

        btnHistorialTramites.setBackground(new java.awt.Color(153, 0, 51));
        btnHistorialTramites.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHistorialTramites.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialTramites.setText("Historial de tramites");
        btnHistorialTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialTramitesActionPerformed(evt);
            }
        });

        btnRegistrarVehiculo.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrarVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegistrarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarVehiculo.setText("Registrar Vehiculo");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHistorialTramites, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTramitePlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTramiteLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnRegistrarVehiculo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrarPersonas)
                        .addGap(215, 215, 215))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTramiteLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTramitePlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialTramites, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarPersonas)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodo oyente que te lleva ala pantalla de busquedaPersona que posteriormente te envia a HistorialTramites.
     * @param evt evento recibido.
     */
    private void btnHistorialTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialTramitesActionPerformed
        this.dispose();
        BusquedaPersona busquedaPersona = new BusquedaPersona(Ventana.HISTORIALTRAMITES);
    }//GEN-LAST:event_btnHistorialTramitesActionPerformed
    /**
     * Metodo oyente que registra las personas.
     * @param evt evento recibido.
     */
    private void btnRegistrarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonasActionPerformed
        try {
            PersonasDAO personasDAO = new PersonasDAO();
            personasDAO.agregarPersonas();
            this.mostrarMensajePersonasGuardadas();
        } catch (PersistenciaException ex) {
            this.mostrarMensajePersonasError();
        }
    }//GEN-LAST:event_btnRegistrarPersonasActionPerformed
    /**
     * Metodo oyente que te lleva ala pantalla de busquedaPersona que posteriormente te envia a TramiteLicencia.
     * @param evt evento recibido.
     */
    private void btnTramiteLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramiteLicenciaActionPerformed
        this.dispose();
        BusquedaPersona busquedaPersona = new BusquedaPersona(Ventana.TRAMITELICENCIAS);
    }//GEN-LAST:event_btnTramiteLicenciaActionPerformed
    /**
     * Metodo oyente que te lleva ala pantalla de busquedaPersona que posteriormente te envia a TramitePlacas.
     * @param evt evento recibido.
     */
    private void btnTramitePlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitePlacasActionPerformed
        this.dispose();
        BusquedaPersona busquedaPersona = new BusquedaPersona(Ventana.TRAMITEPLACAS);
    }//GEN-LAST:event_btnTramitePlacasActionPerformed
    /**
     * Metodo oyente que te lleva ala pantalla de RegistrarVehiculo.
     * @param evt evento recibido.
     */
    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        this.dispose();
        new RegistrarVehiculo(Ventana.MENU);
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed
    /**
     * Metodo oyente que te lleva ala pantalla de GenerarReporte.
     * @param evt evento recibido.
     */
    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        this.dispose();
        new GenerarReporte();
    }//GEN-LAST:event_btnReportesActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorialTramites;
    private javax.swing.JButton btnRegistrarPersonas;
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTramiteLicencia;
    private javax.swing.JButton btnTramitePlacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
