/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantillapantallasproyecto2basedatosavanzadas;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import org.itson.DAO.TramitesDAO;
import org.itson.DAO.VehiculosDAO;
import org.itson.dominio.Estado;
import org.itson.dominio.Licencia;
import org.itson.dominio.Persona;
import org.itson.dominio.TipoLicencia;
import utilidades.Validaciones;
import utilidades.Ventana;

/**
 *
 * @author Zaurus
 */
public class TramiteLicencia extends javax.swing.JFrame {
    private Persona personaTramite;
    private TipoLicencia tipoLicencia;
    private int anosVigencia;
    /**
     * Creates new form TramiteLicencia
     */
    public TramiteLicencia(Persona personaTramite) {
        initComponents();
        this.personaTramite = personaTramite;
        this.setVisible(true);
        String informacion = personaTramite.getRfc() + " " + personaTramite.getNombre() + " "
                + personaTramite.getApellidoPaterno() + " " + personaTramite.getApellidoMaterno();
        txtInformacionPersona.setText(informacion);

    }
     public void mostrarMensajeLicenciaGuardadas() {
        JOptionPane.showMessageDialog(this, "Licencia guardada correctamente",
                "Completado", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void creacionObjeto(){
        Licencia licencia = new Licencia();
        GregorianCalendar fechaActual = new GregorianCalendar();
        GregorianCalendar fechaVencimiento = new GregorianCalendar();
        if(anosVigencia == 1){
           fechaVencimiento.add(Calendar.YEAR, 1);
        }
        if(anosVigencia == 2){
            fechaVencimiento.add(Calendar.YEAR, 2);
        }
        if(anosVigencia == 3){
            fechaVencimiento.add(Calendar.YEAR, 3);
        }
        licencia.setCosto(Float.parseFloat(txtPrecio.getText()));
        licencia.setEstado(Estado.Activo);
        licencia.setFechaExpedicion(fechaActual);
        licencia.setTipoCosto(tipoLicencia);
        licencia.setVigencia(fechaVencimiento);
        licencia.setPersona(personaTramite);
        TramitesDAO tramitesDAO = new TramitesDAO();
        tramitesDAO.registrarLicencia(licencia); 
        this.mostrarMensajeLicenciaGuardadas();
        this.dispose();
        new MenuInicio();
    }
    public boolean acreeditarCampos()
    {
        
        if(btgVigencia.getSelection() != null && btgDiscapacitado.getSelection() != null)
        {
         return true;
        } else {
            String mensaje = "Campo(s) invalido(s) [Formato(s) valido(s)]\n";
            if (btgVigencia.getSelection() == null) {
                mensaje +=   "- Seleccione vigencia [1/2/3]\n";
            }
            if (btgDiscapacitado.getSelection() == null) {
                mensaje +=   "- Seleccione discapacidad [Si/No]\n";
            }
            JOptionPane.showMessageDialog(this, mensaje);
            return false;
        }
        
    
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgVigencia = new javax.swing.ButtonGroup();
        btgDiscapacitado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtInformacionPersona = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbtn1Ano = new javax.swing.JRadioButton();
        rbtn2Ano = new javax.swing.JRadioButton();
        rbtn3Ano = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rbtnSi = new javax.swing.JRadioButton();
        rbtnNo = new javax.swing.JRadioButton();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(564, 564));

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tramite de licencia");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Informacion de la Persona");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        txtInformacionPersona.setEditable(false);
        txtInformacionPersona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtInformacionPersona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInformacionPersona.setBackground(new java.awt.Color(0, 51, 0));
        txtInformacionPersona.setBorder(null);
        txtInformacionPersona.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInformacionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInformacionPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(564, 176));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Discapacitado");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Vigencia");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        btgVigencia.add(rbtn1Ano);
        rbtn1Ano.setText("1 AÑO");
        rbtn1Ano.setBackground(new java.awt.Color(153, 0, 51));
        rbtn1Ano.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rbtn1Ano.setBorderPainted(true);
        rbtn1Ano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtn1Ano.setForeground(new java.awt.Color(255, 255, 255));
        rbtn1Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn1AnoActionPerformed(evt);
            }
        });

        btgVigencia.add(rbtn2Ano);
        rbtn2Ano.setText("2 AÑOS");
        rbtn2Ano.setBackground(new java.awt.Color(153, 0, 51));
        rbtn2Ano.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rbtn2Ano.setBorderPainted(true);
        rbtn2Ano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtn2Ano.setForeground(new java.awt.Color(255, 255, 255));
        rbtn2Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn2AnoActionPerformed(evt);
            }
        });

        btgVigencia.add(rbtn3Ano);
        rbtn3Ano.setText("3 AÑOS");
        rbtn3Ano.setBackground(new java.awt.Color(153, 0, 51));
        rbtn3Ano.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rbtn3Ano.setBorderPainted(true);
        rbtn3Ano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtn3Ano.setForeground(new java.awt.Color(255, 255, 255));
        rbtn3Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn3AnoActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Costo");
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        btgDiscapacitado.add(rbtnSi);
        rbtnSi.setText("Si");
        rbtnSi.setBackground(new java.awt.Color(153, 0, 51));
        rbtnSi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rbtnSi.setBorderPainted(true);
        rbtnSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtnSi.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSiActionPerformed(evt);
            }
        });

        btgDiscapacitado.add(rbtnNo);
        rbtnNo.setText("No");
        rbtnNo.setBackground(new java.awt.Color(153, 0, 51));
        rbtnNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rbtnNo.setBorderPainted(true);
        rbtnNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtnNo.setForeground(new java.awt.Color(255, 255, 255));
        rbtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNoActionPerformed(evt);
            }
        });

        txtPrecio.setEditable(false);
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPrecio.setBackground(new java.awt.Color(51, 51, 51));
        txtPrecio.setBorder(null);
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("$");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbtn2Ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtn1Ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtn3Ano))
                        .addGap(110, 110, 110))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnNo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn1Ano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtn2Ano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn3Ano))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.setBackground(new java.awt.Color(153, 0, 51));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setBackground(new java.awt.Color(153, 0, 51));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn3AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn3AnoActionPerformed
        this.anosVigencia = 3;
        if(rbtnNo.isSelected()){
            txtPrecio.setText("1100");
        }
        if(rbtnSi.isSelected()){
           txtPrecio.setText("700");
        }
    }//GEN-LAST:event_rbtn3AnoActionPerformed

    private void rbtn2AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn2AnoActionPerformed
        this.anosVigencia = 3;
        if(rbtnNo.isSelected()){
            txtPrecio.setText("900");
        }
        if(rbtnSi.isSelected()){
           txtPrecio.setText("500");
        }
    }//GEN-LAST:event_rbtn2AnoActionPerformed

    private void rbtn1AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn1AnoActionPerformed
        this.anosVigencia = 3;
        if(rbtnNo.isSelected()){
            txtPrecio.setText("600");
        }
        if(rbtnSi.isSelected()){
           txtPrecio.setText("200");
        }
    }//GEN-LAST:event_rbtn1AnoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
      if(acreeditarCampos())
      {
        this.creacionObjeto();
      }
      
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        BusquedaPersona busquedaPersona = new BusquedaPersona(Ventana.TRAMITELICENCIAS);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbtnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSiActionPerformed
       this.tipoLicencia = TipoLicencia.Discapacitado;
        if(rbtn1Ano.isSelected()){
           txtPrecio.setText("200");
       }
       if(rbtn2Ano.isSelected()){
           txtPrecio.setText("500");
       }
       if(rbtn3Ano.isSelected()){
           txtPrecio.setText("700");
       }
    }//GEN-LAST:event_rbtnSiActionPerformed

    private void rbtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNoActionPerformed
       this.tipoLicencia = TipoLicencia.Discapacitado;
        if(rbtn1Ano.isSelected()){
           txtPrecio.setText("600");
       }
       if(rbtn2Ano.isSelected()){
           txtPrecio.setText("900");
       }
       if(rbtn3Ano.isSelected()){
           txtPrecio.setText("1100");
       }
    }//GEN-LAST:event_rbtnNoActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDiscapacitado;
    private javax.swing.ButtonGroup btgVigencia;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtn1Ano;
    private javax.swing.JRadioButton rbtn2Ano;
    private javax.swing.JRadioButton rbtn3Ano;
    private javax.swing.JRadioButton rbtnNo;
    private javax.swing.JRadioButton rbtnSi;
    private javax.swing.JTextField txtInformacionPersona;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
